name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deploy folder & Inject API Key
        run: |
          mkdir dist
          cp index2.html dist/
          sed -i 's/__SHARED_API_KEY__/${{ secrets.SHARED_GEMINI_API_KEY }}/g' dist/index2.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
